import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Montserrat, Inter, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased bg-black`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
